; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[hardware]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
lib_ldf_mode = chain+
lib_compat_mode = strict
build_flags =
  -std=gnu++2a
  -Wall
  -fno-exceptions
  -D RGB_ARDUINO
  -D RGB_ARDUINO_NANO
  -D RGB_VEHICLE_CORE_STACK_SIZE=8192
  -D RGB_VEHICLE_CORE_PRIORITY=1
  -D RGB_VEHICLE_CORE_DISABLE=0
build_unflags =
  -std=gnu++11
  -fexceptions
lib_deps=
  bdon/rgblib
  mh-tobi/MCP2515

[env:debug]
extends = hardware
build_flags =
  ${hardware.build_flags}
  -D RGB_DEBUG

[env:release]
extends = hardware
build_flags =
  ${hardware.build_flags}